### ISSUE TITLE
Unable to sponsor project

### ISSUE THREAD

**Issue by soapiestwaffles** [s0d3s/PyAudioWPatch#12]
[comment]: <> (Just paste "x" inside brackets, for example: - [x] Some positive statement)

**What problem are you facing?**

- [ ] audio isn`t recorded
- [ ] audio is recorded with artifacts
- [ ] problem with "silence"
- [x] other

**What is the cause of the error (in your opinion)?**

- [ ] PyAudio\PortAudio bug
- [x] I just need help(or answer)

❗ **Before creating, complete the checklist**:
- [ ] I have provided a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (and checked its correctness)
- [x] I'm sure I fully described the problem

> If the problem is related to the inability to record sound from speakers,
> then before creating this issue, try to first record audio using the provided examples
> (for example, [simple_recording_app.py](https://github.com/s0d3s/PyAudioWPatch/blob/master/examples/pawp_simple_recording_app.py))

### Start your issue here 👇
Sorry for making an issue for something that isn't _really_ an issue, but .... Thank you so much for this project. I'm trying to find a way to 💰sponsor/send you a contribution for PyAudioWPatch since it's saved me a ton of time and works amazingly. ❤️

**Comment by s0d3s** [comment]
Hello👋
I am very glad that you liked my work. And this in itself is sufficient support, more than that I do not need🧐
But if you still want to support me, then I have a [patreon](https://www.patreon.com/s0d3s)
