### ISSUE TITLE
Artifacts when recording without using callbacks

### ISSUE THREAD

**Issue by JiaCYu** [s0d3s/PyAudioWPatch#15]
[comment]: <> (Just paste "x" inside brackets, for example: - [x] Some positive statement)

**What problem are you facing?**

- [ ] audio isn`t recorded
- [x] audio is recorded with artifacts
- [ ] problem with "silence"
- [ ] other

**What is the cause of the error (in your opinion)?**

- [ ] PyAudio\PortAudio bug
- [x] I just need help(or answer)

❗ **Before creating, complete the checklist**:
- [x] I have provided a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (and checked its correctness)
- [x] I'm sure I fully described the problem

> If the problem is related to the inability to record sound from speakers,
> then before creating this issue, try to first record audio using the provided examples
> (for example, [simple_recording_app.py](https://github.com/s0d3s/PyAudioWPatch/blob/master/examples/pawp_simple_recording_app.py))

### Start your issue here 👇

Hi, thank you for the patch! Really love the addition to this old library. For my issue, I'm getting artifacts and sped up audio when I use this library without callbacks.
The example .py file in `examples/pawp_record_wasapi_loopback.py` works perfectly and sound is recorded flawlessly, but when I use `examples/pawp_another_record_wasapi_loopback.py`, artifacts appear in the sound file.

Another version of my code (without using callbacks):
```python
from _spinner_helper import Spinner

import pyaudiowpatch as pyaudio
import wave
import time
duration = 5.0
data_format = pyaudio.paInt16

filename = "loopback_record.wav"
    
    
if __name__ == "__main__":
    with pyaudio.PyAudio() as p, Spinner() as spinner:
        """
        Create PyAudio instance via context manager.
        Spinner is a helper class, for `pretty` output
        """

        try:
            wasapi = p.get_host_api_info_by_type(pyaudio.paWASAPI)
            default_speakers = p.get_device_info_by_index(wasapi['defaultOutputDevice'])
            print("default_speaker: ", default_speakers)
            print(default_speakers)

        except OSError:
            spinner.print("Looks like WASAPI is not available on the system. Exiting...")
            spinner.stop()
            exit()

        except LookupError:
            spinner.print("Default loopback output device not found.\n\nRun `python -m pyaudiowpatch` to check available devices.\nExiting...\n")
            spinner.stop()
            exit()

        RATE = int(default_speakers["defaultSampleRate"])
        SAMPLE_SIZE = p.get_sample_size(data_format)

        if not default_speakers["isLoopbackDevice"]:
            for loopback in p.get_loopback_device_info_generator():
                """
                Try to find loopback device with same name(and [Loopback suffix]).
                Unfortunately, this is the most adequate way at the moment.
                """
                if default_speakers["name"] in loopback["name"]:
                    default_speakers = loopback
                    break
            else:
                spinner.print("Default loopback output device not found.\n\nRun `python -m pyaudiowpatch` to check available devices.\nExiting...\n")
                spinner.stop()
                exit()


        spinner.print(f"Recording from: ({default_speakers['index']}){default_speakers['name']}")
        
        wave_file = wave.open(filename, 'wb')
        wave_file.setnchannels(default_speakers['maxInputChannels'])
        wave_file.setsampwidth(SAMPLE_SIZE)
        wave_file.setframerate(RATE)


        print("Default SPEAKER: ", default_speakers)

        speaker_stream = p.open(format=pyaudio.paInt16,
                channels=default_speakers["maxInputChannels"],
                rate=int(default_speakers["defaultSampleRate"]),
                frames_per_buffer=1024,
                input=True,
                input_device_index=default_speakers["index"],
                # stream_callback=pyaudio_callback
        )

        spinner.print(f"The next {duration} seconds will be written to {filename}")
        for i in range(0, int(RATE / SAMPLE_SIZE * duration)):
            """Record audio step-by-step"""
            data = speaker_stream.read(SAMPLE_SIZE)
            wave_file.writeframes(data)
        
        

        
        wave_file.close()
```

**Comment by sebastiaan-futech** [comment]
I'm having the same issue... Was actually working fine a few hours ago, but now `default_speakers["defaultSampleRate"]` returns `48000`, even though I know it should be `44100`. entering `44100` manually results in an error: `... OSError: [Errno -9997] Invalid sample rate`

**Comment by xjqianqian** [comment]
I have the same problem. To send the audio stream to a websockets for transcribing, a user-defined rate like `16_000` is preferred, but the 'defaultSampleRate' is `48000`.

**Comment by s0d3s** [comment]
@sebastiaan-futech and @xjqianqian 
Hello🖐 
What you are writing about is not a bug. The looback device is not physical, but virtual(it exists only within the PortAudio). The speaker from which you want to record audio and the actual (virtual) looback device that will be used for this - are not the same. The `defaultSampleRate` field contains the current value for the looback device(even if the original one has a different value)

If you want to change the Sample Rate of the final recording, this will have to be done in post-processing. For example using pydub.

**Comment by s0d3s** [comment]
@JiaCYu 
Thanks for your comment and sorry for the long response!

Recording audio directly without a callback is a very unstable feature (even at the level not of PyAudio, but of PortAudio).
And in fact, **under the hood**, PortAudio still uses a callback and writes chunks to a buffer, which are returned on demand (call `stream.read`)
This mode uses more resources and may have more artifacts and lags

The only thing that can fix your problem is to increase the size of the chunks(but this will increase the delay).
But it's better to switch to using a `callback`-mode

P.S. To try to fix this problem you need to patch PortAudio. I don't plan to do this in the near future🌑
