### ISSUE TITLE
Requesting a new release with Python 3.12 compatibility

### ISSUE THREAD

**Issue by vivekuppal** [s0d3s/PyAudioWPatch#16]
**What problem are you facing?**

Cannot use PyAudioWPatch with Python 3.12.0

**What is the cause of the error (in your opinion)?**

- [ ] PyAudio\PortAudio bug
- [ ] I just need help(or answer)
- [x] Do not know

❗ **Before creating, complete the checklist**:
- [x] I have provided a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (and checked its correctness)
- [x] I'm sure I fully described the problem

### Start your issue here 👇
**Attempting to use PyAudioWPatch with Python 3.12.2 gives the following error when installing using pip**

```

(venv) C:\Test>python --version
Python 3.12.2

(venv) C:\Test>pip install PyAudioWPatch
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement PyAudioWPatch (from versions: none)
ERROR: No matching distribution found for PyAudioWPatch

(venv) C:\Test>pip list
Package Version
------- -------
pip     24.0

```

**Comment by s0d3s** [comment]
Hello there🖐
The build for Python 3.12 is ready, but due to spammer attacks, PyPI has temporarily limited the uploading of new packages. As soon as they open access I will post it.

SRC: https://status.python.org/incidents/dc9zsqzrs0bv

**Comment by vivekuppal** [comment]
Confirming that issue is resolved on our end.
Appreciate the help with moving forward on the issue.
