### ISSUE TITLE
Just a issue to let u know your repo is great

### ISSUE THREAD

**Issue by matrix1001** [s0d3s/PyAudioWPatch#17]
searching a loopback recording solution for hours. your work is simple and great. just want you to know it helps a lot.

**Comment by matrix1001** [comment]
maybe you can add more introduction in the readme. for example: pyaudio patch to record system sound on any devices ...

**Comment by s0d3s** [comment]
Hi🖐 
I am very pleased that my lib helped you!

**Comment by s0d3s** [comment]
> maybe you can add more introduction in the readme. for example: pyaudio patch to record system sound on any devices ...

Unfortunately, (W)Patch is only for (W)indows, so "on any devices" won't be true.

I had thoughts of writing a cross-platform analogue🗿 But this will not happen in the near future

**Comment by matrix1001** [comment]
i mean audio devices. your code works even on my bluetooth earphone.  it is a pity that your repo is not easily searchable. 

> > maybe you can add more introduction in the readme. for example: pyaudio patch to record system sound on any devices ...
> 
> Unfortunately, (W)Patch is only for (W)indows, so "on any devices" won't be true.
> 
> I had thoughts of writing a cross-platform analogue🗿 But this will not happen in the near future

**Comment by s0d3s** [comment]
@matrix1001 Thanks for the advice. I'll think about how this can be improved
