### ISSUE TITLE
PyAudioWPatch does not pick up when connect new device such as usb/bluetooth headset

### ISSUE THREAD

**Issue by minh-wp** [s0d3s/PyAudioWPatch#18]
[comment]: <> (Just paste "x" inside brackets, for example: - [x] Some positive statement)

**What problem are you facing?**

- [ ] audio isn`t recorded
- [ ] audio is recorded with artifacts
- [ ] problem with "silence"
- [x ] other

**What is the cause of the error (in your opinion)?**

- [ ] PyAudio\PortAudio bug
- [ ] I just need help(or answer)

❗ **Before creating, complete the checklist**:
- [ ] I have provided a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (and checked its correctness)
- [ ] I'm sure I fully described the problem

> If the problem is related to the inability to record sound from speakers,
> then before creating this issue, try to first record audio using the provided examples
> (for example, [simple_recording_app.py](https://github.com/s0d3s/PyAudioWPatch/blob/master/examples/pawp_simple_recording_app.py))

### Start your issue here 👇
- once PyAudioWPatch is loaded, it only maintains the list of channels at the load time, we can not refresh it to pick up new plug-in devices such as usb/bluetooth headsets.
- It would be great to also able to subscribe (or refresh) to pickup the `defaultOutputDevice` and `defaultInputDevice` when they are changed

**Comment by s0d3s** [comment]
Hi🖐 Adding auto-detection can make the behavior of the library a little confusing, so this feature is rejected.
But maybe I will add to the next release the ability to re-intialize an instance at runtime.

Now you can use Proxy-pattern to control PyAudio instance, and renew it on demand
