### ISSUE TITLE
Is there any way to use SpeechRecognition with wasapi loopback?

### ISSUE THREAD

**Issue by ghost** [s0d3s/PyAudioWPatch#21]
[comment]: <> (Just paste "x" inside brackets, for example: - [x] Some positive statement)

**What problem are you facing?**

- [ ] audio isn`t recorded
- [ ] audio is recorded with artifacts
- [ ] problem with "silence"
- [ x] other

**What is the cause of the error (in your opinion)?**

- [ ] PyAudio\PortAudio bug
- [ x] I just need help(or answer)

❗ **Before creating, complete the checklist**:
- [ ] I have provided a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (and checked its correctness)
- [ x] I'm sure I fully described the problem

> If the problem is related to the inability to record sound from speakers,
> then before creating this issue, try to first record audio using the provided examples
> (for example, [simple_recording_app.py](https://github.com/s0d3s/PyAudioWPatch/blob/master/examples/pawp_simple_recording_app.py))

### Start your issue here 👇
Is there any way to use SpeechRecognition with wasapi?
like this
`
import pyaudiowpatch as pyaudio
import speech_recognition as sr

p = pyaudio.Pyaudio()
recognizer = sr.Recognizer()

default_speakers = p.get_default_wasapi_loopback()
    
rate = int(default_speakers["defaultSampleRate"])
channels = default_speakers["maxInputChannels"]
print(f"Recording from: ({default_speakers['index']}) {rate} {channels} {default_speakers['name']}")

stream = p.open(
        format=data_format,
        channels=channels,
        rate=rate,
        frames_per_buffer=1024,
        input=True,
        input_device_index=default_speakers["index"],
    )

recognizer.listen_in_background(stream.read(4096)) # i tried but doesnt work

`
any help would be appreciated!

**Comment by imposterfromtheamongus** [comment]
(in real time)

**Comment by s0d3s** [comment]
Hi🖐 Its depends on SpeechRecognition. If it can do STT in real-time, then you can do it. In turn, PyAudio can do what you need, but maybe you will need to increase the `frames_per_buffer` size, or do manual buffering

**Comment by imposterfromtheamongus** [comment]
Could you provide me for the code as an example ? Much appreciated!
