### ISSUE TITLE
Works fine but not with some audio

### ISSUE THREAD

**Issue by bylertlaylock** [s0d3s/PyAudioWPatch#3]
Tool works great, but not for my purpose. 

It doesn't seem to be working with Microsoft teams. Do you think this is because of the WASAPI being owned by MS and a crafty workaround to avoid that audio to be recorded?

**Comment by s0d3s** [comment]
**WASAPI** allows you to record any sound that is played on a device _that supports this API_. You probably have _multiple output devices_ on your system. Check that [MS Teams outputs](https://support.microsoft.com/en-us/office/manage-your-device-settings-5b5ca50f-eea2-47b6-a98c-611548528498) sound to the device **from which** you are trying to record sound.

If that doesn't help, please provide more information so I can help:
 - the code with which you are trying to record sound
 - list of available devices (run `python -m pyaudiowpatch` and take a screenshot)
