### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by chenbys** [s0d3s/PyAudioWPatch#7]
Thanks for the awesome codes. But I wonder how to record with the best quality.

I notice that we could set `format=pyaudio.paInt32` or `format=p.get_format_from_width(wf.getsampwidth())`, and what's the difference?
Is the `pyaudio.paFloat32` optimal? 

Is the recorded quality also limited by the speaker device? If so, use `pyaudio.paFloat32` may be unnecessary for some inferior speaker.

Therefore, how can I record my speaker  with the best quality and smallest file size?
Thanks in advance.

**Comment by chenbys** [comment]
BTY, is there any other setting for the best quality and smallest file size?

**Comment by s0d3s** [comment]
Hello🖐

Theoretically - yes, if you take a more capacious data type, then it can accommodate a better record. But in practice, you will not feel much difference in sound. They are just different formats for presenting data. The choice of format depends mainly on what it will be more convenient for you to work with during further processing of the recording.

[source](http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html#a4582d93c2c2e60e12be3d74c5fe00b96)

**Comment by chenbys** [comment]
Thank you very much!
